---
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Australia/Sydney    # optional: Change to your desired timezone
    user: 1000:1000 # optional: Set custom user/group or uid/gid
    networks:
      - proxy
    volumes:
      - ./var/cache/ntfy:/var/cache/ntfy
      - ./etc/ntfy:/etc/ntfy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.entrypoints=http"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.yourdomain.com`)"
      - "traefik.http.middlewares.ntfy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ntfy.middlewares=ntfy-https-redirect"
      - "traefik.http.routers.ntfy-secure.entrypoints=https"
      - "traefik.http.routers.ntfy-secure.rule=Host(`ntfy.yourdomain.com`)"
      - "traefik.http.routers.ntfy-secure.tls=true"
      - "traefik.http.routers.ntfy-secure.service=ntfy"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
   proxy:
     external: true
