---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080  # sabnzbd
      - 9696:9696  # prowlarr
      - 7878:7878  # Radarr
      - 8989:8989  # Sonarr
    volumes:
      - /home/josh/docker/arr-stack/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn # wireguard if used
      - OPENVPN_USER=Username
      - OPENVPN_PASSWORD=Password
      #- WIREGUARD_PRIVATE_KEY= #supplied by NordVPN in your account  
      - SERVER_HOSTNAMES=au-sydney.privacy.network
      - VPN_TYPE=openvpn # wireguard if used
      - UPDATER_PERIOD=24h
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/josh/docker/arr-stack/sabnzbd/config:/config
      - /mnt/media2/downloads:/downloads #optional
      - /mnt/media2/downloads/incomplete:/incomplete-downloads #optional
    restart: unless-stopped
    depends_on:
      - gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    network_mode: "service:gluetun"
    volumes:
      - /home/josh/docker/arr-stack/radarr/data:/config
      - /mnt/media2/movies:/movies #optional
      - /mnt/media2/downloads:/downloads #optional
    restart: unless-stopped
    depends_on:
      - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    network_mode: "service:gluetun"
    volumes:
      - /home/josh/docker/arr-stack/sonarr/data:/config
      - /mnt/media2/tv:/tv #optional
      - /mnt/media2/downloads:/downloads #optional
    restart: unless-stopped
    depends_on:
      - gluetun