services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.entrypoints=http"
      - "traefik.http.routers.beszel.rule=Host(`beszel.yourdomain.com`)"
      - "traefik.http.middlewares.beszel-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.beszel.middlewares=beszel-https-redirect"
      - "traefik.http.routers.beszel-secure.entrypoints=https"
      - "traefik.http.routers.beszel-secure.rule=Host(`beszel.yourdomain.com`)"
      - "traefik.http.routers.beszel-secure.tls=true"
      - "traefik.http.routers.beszel-secure.service=beszel"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.docker.network=proxy"
    volumes:
      - /home/josh/docker/beszel/beszel_data:/beszel_data

networks:
  proxy:
    external: true