---
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /home/josh/docker/dashy/public/conf.yml:/app/user-data/conf.yml
      - /home/josh/docker/dashy/icons:/app/public/item-icons/icons
    ports:
      - 8000:8080
    environment:
      - UID=1000
      - GID=1000
    # Specify restart policy
    restart: unless-stopped
