services:
 dashy:
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /home/josh/docker/dashy/public/conf.yml:/app/user-data/conf.yml
      - /home/josh/docker/dashy/icons:/app/public/item-icons/icons 
    networks:
      - proxy
    environment:
      - UID=1000
      - GID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=http"
      - "traefik.http.routers.dashy.rule=Host(`dashy.podlab.tech`)"
      - "traefik.http.middlewares.dashy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dashy.middlewares=dashy-https-redirect"
      - "traefik.http.routers.dashy-secure.entrypoints=https"
      - "traefik.http.routers.dashy-secure.rule=Host(`dashy.podlab.tech`)"
      - "traefik.http.routers.dashy-secure.tls=true"
      - "traefik.http.routers.dashy-secure.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    # Specify restart policy
    restart: unless-stopped